### PR TITLE
Use flex box style to make buttons and title align center in vertical…

### PR DESCRIPTION
**Pull request by xing-zheng**
I found that the title text of navigation bar is not center aligned in vertical, after reviewing the code, I made some change:

use flex box style to make buttons and title align center in vertical instead of using fixed margin or padding. 

the buttons and title will be center aligned regardless font family / font size or language/locale. 

@Kureev Please review this commit and give me feedback, thank you!

### CODE REVIEW

**Comment by holyxiaoxin** [comment]
+1

**Comment by xing-zheng** [comment]
Thanks! @holyxiaoxin

**Comment by Kureev** [comment]
Thanks, @xing-zheng!

**Comment by xing-zheng** [comment]
My pleasure! @Kureev

**Comment by holyxiaoxin** [comment]
I am still unable to vertical align the title. I am trying this:



```
const titleConfig = (
      <TouchableHighlight style={styles.flexCenter} onPress={() => alert('stubbed title')}>
        <Text>{title}</Text>
      </TouchableHighlight>
    )

return (
      <View>
        <NavigationBar
          style={styles.navBar}
          title={titleConfig}
          leftButton={leftButtonConfig}
          rightButton={rightButtonConfig} />
      </View>
    )

const styles = StyleSheet.create({
  navBar: {
    marginTop: 5,
    marginBottom: 5
  },
  flexCenter: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center'
  }
});
```

image

**Comment by xing-zheng** [comment]
It's not about the title, It's about the leftButton and rightButton, try this:

leftButton={
<View style={{flexDirection:'row', alignItems:'center'}}>
    {renderYourButton()}
</View>
}

**Pull request merged**
