### PR TITLE
Add semicolons per ES6 standard (Babel requires it)

### PR DESCRIPTION
**Pull request by jamiltz**
First of all thanks for making this module!

My application won't compile because semicolons were missing. It was working yesterday though. I'm thinking it could be related to https://github.com/babel/babel/pull/3225

### CODE REVIEW

**Comment by grabbou** [comment]
It currently compiles with 0.17 (not this module, but my own class properties)

**Comment by Kureev** [comment]
It requires to place `;` after class variables definition, @grabbou

**Comment by Kureev** [comment]
thanks, @jamiltz!

**Comment by Kureev** [comment]
Released in `1.1.6`

**Comment by jamiltz** [comment]
:+1:

**Pull request merged**
