### PR TITLE
React API must be now required from react package (previously a warning on 0.25)

### PR DESCRIPTION
**Pull request by gargamelius**
See https://github.com/facebook/react-native/releases/tag/v0.25.1

This will become a breaking change in 0.26+

### CODE REVIEW

**Comment by samin** [comment]
PropTypes also belongs to the React API (not React Native)

**Comment by gargamelius** [comment]
Updated. Thanks.

**Comment by sibeliusseraphini** [comment]
👍

**Comment by sibeliusseraphini** [comment]
@Kureev could you please review and publish a new version?

**Comment by grabbou** [comment]
@Kureev is now on holidays. I am going to take care of it later today. If I don't get back to you in few days after releasing it, assume I got killed by him :trollface:

**Comment by Kureev** [comment]
(Mike is still alive)

**Comment by Kureev** [comment]
published in `1.5.0`

**Comment by grabbou** [comment]
You were faster then me 💨

**Pull request merged**
